package dao.inheritance4;
// default package
// Generated Jan 10, 2023, 10:26:34 AM by Hibernate Tools 6.0.0.Alpha2


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="inheritance4"
)
public class Student4 extends Person4 {


    // private Integer id;
     private String department;

    public Student4() {
    }

    public Student4(String department) {
       this.department = department;
    }
   
    // @Id @GeneratedValue(strategy=IDENTITY)

    
    // @Column(name="id", unique=true, nullable=false)
    // public Integer getId() {
    //     return this.id;
    // }
    
    // public void setId(Integer id) {
    //     this.id = id;
    // }

    
    @Column(name="department", nullable=false, length=45)
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }




}


