package dao.inheritance4;
// default package
// Generated Jan 10, 2023, 10:26:34 AM by Hibernate Tools 6.0.0.Alpha2


import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name="teacher"
    ,catalog="inheritance4"
)
public class Teacher4 extends Person4 {


    // private Integer id;
     private Date hireDate;

    public Teacher4() {
    }

    public Teacher4(Date hireDate) {
       this.hireDate = hireDate;
    }
   
    // @Id @GeneratedValue(strategy=IDENTITY)

    
    // @Column(name="id", unique=true, nullable=false)
    // public Integer getId() {
    //     return this.id;
    // }
    
    // public void setId(Integer id) {
    //     this.id = id;
    // }

    @Temporal(TemporalType.DATE)
    @Column(name="hire_date", nullable=false, length=10)
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }




}


