// default package
// Generated Jan 10, 2023, 12:51:06 AM by Hibernate Tools 6.0.0.Alpha2
package dao.inheritance2;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="inheritance2"
)
public class Student2 extends dao.inheritance2.Person2 {

     private String department;

    public Student2() {
    }

    public Student2(String department) {
       this.department = department;
    }
   
    
    @Column(name="department", nullable=false, length=45)
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }




}


