// default package
// Generated Jan 10, 2023, 12:51:06 AM by Hibernate Tools 6.0.0.Alpha2
package dao.inheritance2;

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name="teacher"
    ,catalog="inheritance2"
)
public class Teacher2 extends dao.inheritance2.Person2 {


     //private Integer id;
     private Date hireDate;

    public Teacher2() {
    }

    public Teacher2(Date hireDate) {
       this.hireDate = hireDate;
    }
   
    //  @Id @GeneratedValue(strategy=IDENTITY)

    
    // @Column(name="id", unique=true, nullable=false)
    // public Integer getId() {
    //     return this.id;
    // }
    
    // public void setId(Integer id) {
    //     this.id = id;
    // }


    @Temporal(TemporalType.DATE)
    @Column(name="hire_date", nullable=false, length=10)
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }




}


