package dao.inheritance3;
// default package
// Generated Jan 10, 2023, 1:26:45 AM by Hibernate Tools 6.0.0.Alpha2


import jakarta.persistence.Column;
import jakarta.persistence.DiscriminatorColumn;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.Table;
import jakarta.persistence.InheritanceType;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
    ,catalog="inheritance3"
)
@Inheritance(strategy=InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name="person_type")
public abstract class Person3 implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;

    public Person3() {
    }

	
    public Person3(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="first_name", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }





}


