// default package
// Generated Jan 10, 2023, 12:51:06 AM by Hibernate Tools 6.0.0.Alpha2
package dao.inheritance3;

import jakarta.persistence.Column;
import jakarta.persistence.DiscriminatorValue;
import jakarta.persistence.Entity;

/**
 * Student generated by hbm2java
 */
@Entity
@DiscriminatorValue("ST")

public class Student3 extends Person3 {

     private String department;

    public Student3() {
    }

    public Student3(String department) {
       this.department = department;
    }
   
    
    @Column(name="department", nullable=true, length=45)
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }




}


