// default package
// Generated Jan 10, 2023, 12:51:06 AM by Hibernate Tools 6.0.0.Alpha2
package dao.inheritance3;

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.DiscriminatorValue;
import jakarta.persistence.Entity;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Teacher generated by hbm2java
 */
@Entity
@DiscriminatorValue("TA")

public class Teacher3 extends Person3 {

     private Date hire_date;

    public Teacher3() {
    }

    public Teacher3(Date hireDate) {
       this.hire_date = hireDate;
    }
   
    @Temporal(TemporalType.DATE)
    @Column(name="hire_date", nullable=true, length=10)
    public Date getHireDate() {
        return this.hire_date;
    }
    
    public void setHireDate(Date hireDate) {
        this.hire_date = hireDate;
    }


}


